### ISSUE TITLE
Importing electrum bech32 address fails

### ISSUE THREAD

**Issue by FieserKiller** [cleanblockchain/Bitcoin-CBC#1]
I try to import the private key from an electrum wallet. It is a bech32 address which held some btc at block 498754. 
importing address directly via importprivkey in console did not work and printed error -5, so I converted the key format using this script:
https://github.com/spesmilo/electrum/issues/3667

now the response to importprivkey is "null" and funds do not show up.

So, is bech32 not supported? and idea what I'm doing wrong? 
btw. Address in question is: bc1qepata2thny8lhjzqd7vqhsecn6snxnfvsdkuj9

**Comment by dekantor** [comment]
That's right, they were ignored (bech32 addresses) because of their small numbers. But everyone can receive his funds on request, I just sent to your address 20.00872486 BCBC
